name: TentakelPlugin
main: de.schoschi.ichstehaufgayhentaimittentakeln.TentakelPlugin
version: 1.0

libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.6.10"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.0"

commands:
  challenge:
